### ISSUE TITLE
加载ms_adapter.bin报错

### ISSUE THREAD

**Issue by JoshonSmith** [MS-Diffusion/MS-Diffusion#2]
加载ms_adapter.bin报错
加载MSAdapter类的权重报错：

```
Traceback (most recent call last):
  File "MS-Diffusion/inference.py", line 66, in <module>
    ms_model = MSAdapter(pipe.unet, image_proj_model, ckpt_path=ms_ckpt, device=device, num_tokens=num_tokens)
  File "MS-Diffusion/msdiffusion/models/model.py", line 36, in __init__
    self.load_from_checkpoint(ckpt_path)
  File "MS-Diffusion/msdiffusion/models/model.py", line 49, in load_from_checkpoint
    self.image_proj_model.load_state_dict(state_dict["image_proj"], strict=True)
  File "/software/anaconda3/envs/msdiffusion/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Resampler:
        size mismatch for proj_in.weight: copying a param with shape torch.Size([1280, 1664]) from checkpoint, the shape in current model is torch.Size([1280, 1024]).
```

**Comment by sherrydoge** [comment]
Please check the initialization of Resampler https://github.com/MS-Diffusion/MS-Diffusion/blob/15318ee73583e8d510be81b2efd0c7ba05797d4a/inference.py#L51C1-L62C34. Since we use the [CLIP-G](https://huggingface.co/laion/CLIP-ViT-bigG-14-laion2B-39B-b160k) image encoder, it should be set that `dim=1280` and `embedding_dim=image_encoder.config.hidden_size` (1664 for CLIP-G). You should also check if the image encoder is right.
